### ISSUE TITLE
PayloadTooLargeError: request entity too large When restoring a backup

### ISSUE THREAD

**Issue by badrow** [standardnotes/syncing-server#192] opened 2021-04-15 07:35 UTC
I'm trying to upload my standardnotes backup (1800 notes approximately, some big notes) and I get an unknown syncing error from the client.
The server log is showing this : 

```
api-gateway_1               | PayloadTooLargeError: request entity too large
api-gateway_1               |     at readStream (/var/www/node_modules/raw-body/index.js:155:17)
api-gateway_1               |     at getRawBody (/var/www/node_modules/raw-body/index.js:108:12)
api-gateway_1               |     at read (/var/www/node_modules/body-parser/lib/read.js:77:3)
api-gateway_1               |     at jsonParser (/var/www/node_modules/body-parser/lib/types/json.js:135:5)
api-gateway_1               |     at Layer.handle [as handle_request] (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/layer.js:95:5)
api-gateway_1               |     at trim_prefix (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/index.js:317:13)
api-gateway_1               |     at /var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/index.js:284:7
api-gateway_1               |     at Function.process_params (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/index.js:335:12)
api-gateway_1               |     at next (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/router/index.js:275:10)
api-gateway_1               |     at internalNext (/var/www/node_modules/helmet/dist/index.js:86:6)
a
```

Notes : The server is correctly working when I create a simple new note and I don't try to import my backup.

Any idea please ?

**Comment by JaspalSuri** [comment] 2021-04-15 08:09
Hi @badrow, we're aware of this issue and it's on our todo list. I will reach out to you when a fix is available.

**Comment by karolsojko** [comment] 2021-04-15 08:27
Closing as duplicate of https://github.com/standardnotes/forum/issues/1281

**Closed by karolsojko** 2021-04-15 08:27 UTC
