### ISSUE TITLE
More permissive reauthorization timeout

### ISSUE THREAD

**Issue by valantur** [standardnotes/syncing-server#173] opened 2021-01-27 00:01 UTC
Can you please let us configure a way to prevent the syncing server from requiring authorization so often?

I like leaving my notes opened on my Mac all day and since updating the server to the latest version I noticed that I need to re-enter my credentials 6-7 times a day. I understand the security aspect here, but having to type my email and a really hard to guess password this many times is very annoying. Same with my phone. When I need to look at a note, I open the app just to find the Authorization the popup and I need to open my password manager to copy the password... very time consuming.

I wish there was a way to set up the syncing-server not to require reauthorization so often (or ever). I'd rather have the option to choose between sub-par security and ease of use.

Thanks!

**Comment by JaspalSuri** [comment] 2021-01-27 10:50
Hi @valantur,

Please proceed with the following recommendation by @karolsojko:
>If you’re using the `standardnotes/syncing-server:stable` image please switch to `standardnotes/syncing-server` or `standardnotes/syncing-server:latest` (which is the same thing). Although the stable tag will still be available, it will no longer be populated with newer releases.

**Comment by karolsojko** [comment] 2021-01-27 11:55
This might also help: https://github.com/standardnotes/syncing-server/issues/143#issuecomment-737763083

**Comment by valantur** [comment] 2021-01-27 17:01
Hi guys thanks for getting back to me.

The thing is that I'm not using Docker at all (I can't run Docker on this server). I'm cloning and compiling when I see a new release pushed out. Everything is running on a debian LXC virtual machine.

Also, my .env already has `RAILS_ENV=production` in it, and it used to work just fine until I re-compiled and updated the server about a week ago.

Any other ideas? Is the Docker image set up differently than when compiling from source?

**Comment by valantur** [comment] 2021-02-02 19:06
Could you at least tell me if I wouldn't have to re-authorize my clients every few hours if I start using your Docker image?

**Comment by karolsojko** [comment] 2021-02-03 09:07
Well, we use Docker images on production and development setup so that's the only way to ensure you are running on the same environment as we do. It should work without having to log in every few hours if the env vars are properly set up.

**Comment by ryanbutterfield** [comment] 2021-02-09 03:25
I am experiencing the same issue since I upgraded my previous docker image to the newly suggested `standardnotes/syncing-server:latest`. 

Thus I don't believe moving to the docker images will solve @valantur 's issue as it happens with me also.

The reauthentication dialogs appear on both the desktop and mobile apps. Every hour or so.

Before the upgrade I only ever had to authenticate once and never again. It would be nice to be able to go back to that setup.

**Comment by karolsojko** [comment] 2021-02-09 08:55
@ryanbutterfield what value of `RAILS_ENV` do you have in your running setup?

**Comment by ryanbutterfield** [comment] 2021-02-09 23:15
@karolsojko It was `development`, but I changed it to `production` and it's still occuring. Note that it's not defined in your `docker-compose.yml` and seems to default to `development`. Regardless, that doesn't seem to be the cause of the issue.

**Comment by valantur** [comment] 2021-02-09 23:32
@ryanbutterfield I ended up fixing the issue by manually adding `-e production` my init.d service file. In other words, newer versions of the syncing server do not seem to read the RAILS_ENV variable properly. At least that's my experience because it all started when I updated the server. I hope this helps.

**Comment by ryanbutterfield** [comment] 2021-02-10 03:38
Update: `RAILS_ENV` to `production` fixes the issue on docker. Not sure how it ever got set to `development` unless it's the default, or was an old default?

**Comment by karolsojko** [comment] 2021-02-11 08:45
it is the default value and it's fetched from the env file:  https://github.com/standardnotes/syncing-server/blob/develop/.env.sample#L12

**Comment by karolsojko** [comment] 2021-02-11 08:46
Closing this. Feel free to reopne if needed

**Closed by karolsojko** 2021-02-11 08:46 UTC
